// <auto-generated />
namespace InstituteOfTechnology.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class StudenCourse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudenCourse));
        
        string IMigrationMetadata.Id
        {
            get { return "202111140150570_StudenCourse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
