// <auto-generated />
namespace InstituteOfTechnology.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Studentcourse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Studentcourse));
        
        string IMigrationMetadata.Id
        {
            get { return "202111141305262_Studentcourse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
